version: "3.9"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bingemate
    volumes:
      - ./data/db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app
    restart: always
    deploy:
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 150M
    ports:
      - "8080:8080"
    depends_on:
      - db
