version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bingemate
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    networks:
      - postgres


networks:
  postgres:
    driver: bridge