"%local":
  quarkus:
    package:
      type: fast-jar
    smallrye-openapi:
      path: /document
      store-schema-directory: docs/schema
    datasource:
      db-kind: postgresql
      username: postgres
      password: postgres
      jdbc:
        url: jdbc:postgresql://localhost:5432/bingemate
    hibernate-orm:
      database:
        generation: update

"%env":
  quarkus:
    package:
      type: fast-jar
    datasource:
      db-kind: ${DB_KIND}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      jdbc:
        url: jdbc:${DB_KIND}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    hibernate-orm:
      database:
        generation: update